# Generated by Django 2.1 on 2020-06-02 03:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 3, 10, 20, 996851, tzinfo=utc)),
        ),
    ]
